name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Print go version (test)
        run: go version
      - name: Run unit tests
        run: go test ./... -cover
      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest
      - name: Run gosec
        run: $(go env GOPATH)/bin/gosec ./...

  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Print go version (style)
        run: go version
      - name: Run go fmt
        run: go fmt ./...
      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
      - name: Run staticcheck
        run: $(go env GOPATH)/bin/staticcheck ./...
